import React from "react";
import { Link } from "react-router-dom";
import Footer from "../components/Footer";
const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-gray-100 font-sans">
      {/* Header Section */}
      <header className="bg-white shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <h1 className="text-4xl font-bold text-gray-900 font-serif tracking-tight">
            Privacy Policy
          </h1>
          <p className="text-xl text-gray-500 mt-3 font-light">Living Luxura</p>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="bg-white rounded-xl shadow-xl p-10 transition-all duration-300 hover:shadow-2xl">
          <section className="mb-16">
            <p className="text-gray-600 leading-relaxed text-lg">
              This Privacy Policy describes Our policies and procedures on the
              collection, use, and disclosure of Your information when You
              respond to our advertisements and tells You about Your privacy
              rights and how the law protects You. We use Your Personal Data to
              contact and support you, as well as to provide and improve the
              Service. By using the Service, You agree to the collection and use
              of information in accordance with this Privacy Policy.
            </p>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Interpretation and Definitions
            </h2>
            <h3 className="text-2xl font-medium text-gray-800 mb-3">
              Interpretation
            </h3>
            <p className="text-gray-600 leading-relaxed text-lg">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
            <h3 className="text-2xl font-medium text-gray-800 mt-8 mb-3">
              Definitions
            </h3>
            <ul className="list-disc pl-8 text-gray-600 leading-relaxed text-lg">
              <li>
                <strong>Company</strong> (referred to as either "the Company",
                "We", "Us" or "Our" in this Agreement) refers to Living Luxura.
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone, or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the advertisement, website,
                or application.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal
                person who processes the data on behalf of the Company.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit).
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the
                Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Collecting and Using Your Personal Data
            </h2>
            <h3 className="text-2xl font-medium text-gray-800 mb-3">
              Types of Data Collected
            </h3>
            <h4 className="text-xl font-medium text-gray-800 mb-3">
              Personal Data
            </h4>
            <p className="text-gray-600 leading-relaxed text-lg">
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </p>
            <ul className="list-disc pl-8 text-gray-600 leading-relaxed text-lg">
              <li>First name and last name</li>
              <li>Email address</li>
              <li>Phone number</li>
              <li>Location details such as your address, city, or country</li>
              <li>
                Any other data such as personal preferences, requirements, or
                comments
              </li>
            </ul>
            <h4 className="text-xl font-medium text-gray-800 mt-8 mb-3">
              Use of Your Personal Data
            </h4>
            <p className="text-gray-600 leading-relaxed text-lg">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="list-disc pl-8 text-gray-600 leading-relaxed text-lg">
              <li>
                To provide and maintain our Service, including to monitor the
                usage of our Service.
              </li>
              <li>
                To manage Your Account: to manage Your registration as a user of
                the Service.
              </li>
              <li>
                For the performance of a contract: the development, compliance
                and undertaking of the purchase contract for the products, items
                or services You have purchased or of any other contract with Us
                through the Service.
              </li>
              <li>
                To contact You: To contact You by email, telephone calls, SMS,
                or other equivalent forms of electronic communication.
              </li>
              <li>
                To provide You with news, special offers and general information
                about other goods, services and events which we offer.
              </li>
              <li>
                To manage Your requests: To attend and manage Your requests to
                Us.
              </li>
              <li>
                For business transfers: We may use Your information to evaluate
                or conduct a merger, divestiture, restructuring, reorganization,
                dissolution, or other sale or transfer of some or all of Our
                assets.
              </li>
              <li>
                For other purposes: We may use Your information for other
                purposes, such as data analysis, identifying usage trends,
                determining the effectiveness of our promotional campaigns and
                to evaluate and improve our Service, products, services,
                marketing and your experience.
              </li>
            </ul>
            <p className="text-gray-600 leading-relaxed text-lg mt-4">
              We may share Your personal information in the following
              situations:
            </p>
            <ul className="list-disc pl-8 text-gray-600 leading-relaxed text-lg">
              <li>
                <strong>With Service Providers:</strong> We may share Your
                personal information with Service Providers to monitor and
                analyze the use of our Service, to contact You.
              </li>
              <li>
                <strong>For business transfers:</strong> We may share or
                transfer Your personal information in connection with, or during
                negotiations of, any merger, sale of Company assets, financing,
                or acquisition.
              </li>
              <li>
                <strong>With Affiliates:</strong> We may share Your information
                with Our affiliates, in which case we will require those
                affiliates to honor this Privacy Policy.
              </li>
              <li>
                <strong>With business partners:</strong> We may share Your
                information with Our business partners to offer You certain
                products, services or promotions.
              </li>
              <li>
                <strong>With other users:</strong> when You share personal
                information or otherwise interact in the public areas with other
                users, such information may be viewed by all users and may be
                publicly distributed outside.
              </li>
              <li>
                <strong>With Your consent:</strong> We may disclose Your
                personal information for any other purpose with Your consent.
              </li>
            </ul>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Retention of Your Personal Data
            </h2>
            <p className="text-gray-600 leading-relaxed text-lg">
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use Your Personal Data to the extent necessary to
              comply with our legal obligations, resolve disputes, and enforce
              our legal agreements and policies.
            </p>
            <p className="text-gray-600 leading-relaxed text-lg mt-4">
              The Company will also retain Usage Data for internal analysis
              purposes.
            </p>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Transfer of Your Personal Data
            </h2>
            <p className="text-gray-600 leading-relaxed text-lg">
              Your information, including Personal Data, is processed at the
              Company's operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to — and maintained on — computers
              located outside of Your state, province, country or other
              governmental jurisdiction where the data protection laws may
              differ than those from Your jurisdiction.
            </p>
            <p className="text-gray-600 leading-relaxed text-lg mt-4">
              Your consent to this Privacy Policy followed by Your submission of
              such information represents Your agreement to that transfer.
            </p>
            <p className="text-gray-600 leading-relaxed text-lg mt-4">
              The Company will take all steps reasonably necessary to ensure
              that Your data is treated securely and in accordance with this
              Privacy Policy and no transfer of Your Personal Data will take
              place to an organization or a country unless there are adequate
              controls in place including the security of Your data and other
              personal information.
            </p>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Disclosure of Your Personal Data
            </h2>
            <h3 className="text-2xl font-medium text-gray-800 mb-3">
              Law enforcement
            </h3>
            <p className="text-gray-600 leading-relaxed text-lg">
              Under certain circumstances, the Company may be required to
              disclose Your Personal Data if required to do so by law or in
              response to valid requests by public authorities (e.g. a court or
              a government agency).
            </p>
            <h3 className="text-2xl font-medium text-gray-800 mt-8 mb-3">
              Other legal requirements
            </h3>
            <p className="text-gray-600 leading-relaxed text-lg">
              The Company may disclose Your Personal Data in the good faith
              belief that such action is necessary to:
            </p>
            <ul className="list-disc pl-8 text-gray-600 leading-relaxed text-lg">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>
                Prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                Protect the personal safety of Users of the Service or the
                public
              </li>
              <li>Protect against legal liability</li>
            </ul>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Security of Your Personal Data
            </h2>
            <p className="text-gray-600 leading-relaxed text-lg">
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security.
            </p>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Links to Other Websites
            </h2>
            <p className="text-gray-600 leading-relaxed text-lg">
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third party link, You will be
              directed to that third party's site. We strongly advise You to
              review the Privacy Policy of every site You visit.
            </p>
            <p className="text-gray-600 leading-relaxed text-lg mt-4">
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </p>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Changes to this Privacy Policy
            </h2>
            <p className="text-gray-600 leading-relaxed text-lg">
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="text-gray-600 leading-relaxed text-lg mt-4">
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
            <p className="text-gray-600 leading-relaxed text-lg mt-4">
              This Privacy Policy was last updated on 2025/06/18 13:33:49
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-semibold text-gray-900 font-serif mb-6 border-b-2 border-gray-200 pb-2">
              Contact Us
            </h2>
            <p className="text-gray-600 leading-relaxed text-lg">
              If you have any questions about this Privacy Policy, You can
              contact us via email at{" "}
              <a
                href="mailto:connect@marketingbirbal.com"
                className="text-indigo-600 hover:text-indigo-800 transition-colors duration-200"
              >
                connect@marketingbirbal.com
              </a>
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
